// <auto-generated />
using System;
using Autoveod_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autoveod_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Autoveod_MVC.Models.Autovedu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Alguspunkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuhtEesnimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuhtPerenimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KohalejoudmiseAeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lõpppunkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tellija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valmis")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Autoveod");
                });
#pragma warning restore 612, 618
        }
    }
}
